### ISSUE TITLE
Wrong bits referred to in sctrctl

### ISSUE THREAD

**Issue by jhauser-us** [riscv/riscv-control-transfer-records#15]
Section 2.2 says:
> Bits 0 and 8 in `sctrctl` are read-only 0.

Since those fields moved, I believe it should now be bits 2 and 9.

**Comment by bcstrongx** [comment]
Somehow I didn't see this.  But yes, I'll make the fix, thanks.

**Comment by bcstrongx** [comment]
Resolved by https://github.com/riscv/riscv-control-transfer-records/pull/23
