### ISSUE TITLE
"RAS Emulation Mode" should be "RAS Mode"?

### ISSUE THREAD

**Issue by jhauser-us** [riscv/riscv-control-transfer-records#18]
Does RAS Emulation Mode actually emulate anything?  Wouldn't this be better called simply "RAS Mode"?

**Comment by bcstrongx** [comment]
I'd argue that, when RASEMU=1, the CTR buffer is emulating a return-address stack (RAS).  Returns do not actually use the addresses pushed onto it, so it is not an actual RAS.

**Comment by bcstrongx** [comment]
Let me know if you disagree John, otherwise I'll close the issue at the end of this week.
