### ISSUE TITLE
Drop superfluous condition on S-mode being implemented

### ISSUE THREAD

**Issue by jhauser-us** [riscv/riscv-control-transfer-records#20]
Section 6.1.2, "External Traps", says:
> `sctrctl`.STE must be implemented if S-mode is implemented

But S-mode is now required, so the condition is superfluous.

**Comment by bcstrongx** [comment]
Resolved by https://github.com/riscv/riscv-control-transfer-records/commit/120b421d39d8ddf022e9684e77fdf805dbcc21e5
