### ISSUE TITLE
Transfer records are added to the wrong end of the FIFO?

### ISSUE THREAD

**Issue by jhauser-us** [riscv/riscv-control-transfer-records#32]
Chapter 1, "Introduction", says:
>CTR defines a circular (FIFO) buffer.

and:
>Recorded transfers are inserted to the head of the buffer,

Usually entries are said to be added to a FIFO (a queue) at the *tail* and removed from the head.  (Think of what it means to be at the head of a queue.)

Presumably, for "RAS emulation mode", recorded transfers are added at the head of the buffer, since that is a stack (LIFO).

**Comment by bcstrongx** [comment]
Interesting, I have always said it the other way, where the tail pointer is the oldest entry (read pointer) and the head pointer is the newest (or where the next will be written).  

On a quick search, I see docs that agree with me:
https://www.kernel.org/doc/html/v6.1/core-api/circular-buffers.html

And with you:
https://www.cs.umb.edu/~kamaral/cs240/lectures/CS240-Lecture-17.pptx#:~:text=Here%20we%20include%20two%20indexes,the%20freshest%20element%20will%20go.

And some that, confusingly, seem to flip-flop:
https://www.baeldung.com/cs/circular-buffer

We could opt to avoid confusion by omitting references to head/tail altogether, saying something like:

> Recorded transfers are inserted **at the write pointer, which is then incremented,** while older [...]

Do you think this warrants a new release version?

**Comment by jhauser-us** [comment]
> On a quick search, I see docs that agree with me:

IMHO, some mistakes are common, but still wrong.

While Wikipedia isn't guaranteed to be perfectly authoritative either, nevertheless see:
https://en.wikipedia.org/wiki/FIFO_(computing_and_electronics)
https://en.wikipedia.org/wiki/Queue_(abstract_data_type)

Your suggested fix seems good to me.

> Do you think this warrants a new release version?

I don't.  I think this easily counts as an editorial improvement that can be made at any time.

**Comment by bcstrongx** [comment]
Okay, I'll add the clarification at the conclusion of public review.
