### ISSUE TITLE
Questions about the timing of setting sctrstatus.FROZEN when LCOFI occurs

### ISSUE THREAD

**Issue by jasonchien1996** [riscv/riscv-control-transfer-records#37]
Assume smaia and ssaia are enabled and sctrctl.LCOFIFRZ is set. There are multiple pending interrupts, none of which is a LCOFI, so sctrstatus.FROZEN will not be set when the trap occurs. If a LCOFI occurs **after the mode is switched and before SW reads stopi**, when SW reads stopi, SW gets 0xd IID, which is LCOFI, from stopi. According to section 6.5, sctrstatus.FROZEN is **NOT** set.

1. Is this an expected behavior?
2. If the answer to the first question is NO, is the goal here to set FROZEN bit as soon as a LCOFI occurs rather than a trap occurs?
3. Following qeustion 2, should we revise the description in section 6.5?

**Comment by bcstrongx** [comment]
Conclusion from [this thread](https://lists.riscv.org/g/tech-control-transfer-records/message/366) is that no behavior changes are warranted, but additional clarification will be added to the spec.
